name: brighter_you
description: Brighter You Mobile App.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  introduction_screen: ^3.0.0
  snippet_coder_utils: ^1.0.12
  api_cache_manager: ^1.0.2
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  flutter_native_splash: ^1.3.2

flutter_icons: 
  image_path: "assets/idea.png"
  android: true
  ios: true

flutter_native_splash:
  #color: "#303F9F"
  color: "#9FA8DA"
  image: assets/idea.png
  android: true
  ios: true
  android_gravity: fill

flutter:

  uses-material-design: true

  assets:     
    - assets/brighter_you_logo.png
    - assets/idea.png

 
