name: brighter_you
description: Brighter You Mobile App.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  api_cache_manager: ^1.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  fluttertoast: ^8.0.8
  google_fonts: ^2.3.1
  http: ^0.13.4
  introduction_screen: ^3.0.0
  shared_preferences: ^2.0.13
  snippet_coder_utils: ^1.0.12

dev_dependencies:
  flutter_lints: ^1.0.0

  flutter_native_splash: ^1.3.2
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/idea.png"
  android: true
  ios: true

flutter_native_splash:
  background_image: assets/splash.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/
